- Project.toml
- src/DocumenterCitations.jl
This patch changes the indirect dependency on `OrderedCollections` ( `DataStructures` -> `OrderedCollections`) to a direct dependency on `OrderedCollections`.
> Change `DataStructures` to `OrderedCollections`

- docs/make.jl
- src/DocumenterCitations.jl
This is a temporary warning to transition users through the 1.0 breaking change of the default style from author-year to numeric. It can be removed in later releases.
> Emit a warning when using the default style

- docs/src/gallery.md
- docs/src/index.md
- docs/src/syntax.md
This fixes just a small typo and a few markdown linter warnings.
> Fix a typo and a bit of Markdown.

- src/bibliography.jl
- src/citations.jl
This patch homogenizes the verbosity to that of Documenter. By default, one message per Documenter pipeline is shown (with at-info) and everything else is at-debug.
> Adjust the verbosity of log messages a bit

- src/formatting.jl
- test/test_formatting.jl
We should not disregard the names of all authors after the first three. This is one approach to handle this, i.e. add a "+" after the third character, if there are more names left out.
> Show "+" in alpha style for 4+ names

- src/formatting.jl
If some bib entry does not contain a year (e.g. some website included as a `@Misc`), currently DocumenterCitations prints " ()" after the entry. This PR removes that.
> Do not print non-existing years

- NEWS.md
- docs/latex/numeric.tex
- docs/src/gallery.md
- docs/src/refs.bib
- docs/src/syntax.md
- src/DocumenterCitations.jl
- src/bibliography.jl
- src/citations.jl
- src/formatting.jl
- test/Project.toml
- test/init.jl
- test/test_formatting.jl
Closes #20
There is also a workaround for https://github.com/Humans-of-Julia/BibInternal.jl/issues/22. If @Azzaare can merge https://github.com/Humans-of-Julia/BibInternal.jl/issues/23 before we merge this, I can remove the monkeypatched `Bibliography.BibInternal.make_bibtex_entry`.
I've also rewritten the "Syntax for the .bib file" section in the documentation a bit to include some of the discussion in #15, with some tips on how to write a "good" `.bib` file.
Currently, this builds on top of PR #31. Once that is merged, I will rebase.
> Add support for `note` and `eprint` fields

- NEWS.md
- docs/src/refs.bib
- docs/src/syntax.md
- src/formatting.jl
- test/test_formatting.jl
- test/test_formatting/preprints.bib
> Add support for biorXiv and HAL preprint servers

- .github/workflows/ci.yml
- NEWS.md
- Project.toml
- docs/make.jl
- src/citations.jl
- test/runtests.jl
- test/test_collect_from_docstrings.jl
- test/test_collect_from_docstrings/src/index.md
- test/test_collect_from_docstrings/src/references.md
- test/test_undefined_citations.jl
- test/test_undefined_citations/src/index.md
- test/test_undefined_citations/src/references.md
Properly recurse into docstrings when collecting citations.
This adds a test that having a reference that is only cited in a docstrings works as expected.
Also adds a test that the error generated when there is an actual missing reference still correctly percolates up to `makedocs`.
Closes #39
> Collect citations from docstrings

- NEWS.md
- docs/src/index.md
- src/DocumenterCitations.jl
- src/bibliography.jl
- src/citations.jl
- test/run_makedocs.jl
- test/runtests.jl
- test/test_collect_from_docstrings.jl
- test/test_content_block.jl
- test/test_integration.jl
- test/test_keys_with_underscores.jl
- test/test_undefined_citations.jl
Use an independent `AnchorMap` to keep track of targets in the canonical `@bibliography` blocks.
Closes #16
> Fix incompatibility of `@bibliography` and `@contents`

- NEWS.md
- docs/src/syntax.md
- src/DocumenterCitations.jl
- src/expand_bibliography.jl
- test/file_content.jl
- test/runtests.jl
- test/test_bibliography_block_pages.jl
- test/test_bibliography_block_pages/src/addendum.md
- test/test_bibliography_block_pages/src/index.md
- test/test_bibliography_block_pages/src/part1/section1/p1_s1_page.md
- test/test_bibliography_block_pages/src/part1/section2/p1_s2_page.md
- test/test_bibliography_block_pages/src/part2/section1/p2_s1_page.md
- test/test_bibliography_block_pages/src/part2/section2/p2_s2_page.md
- test/test_bibliography_block_pages/src/part3/section1/p3_s1_page.md
- test/test_bibliography_block_pages/src/part3/section2/invalidpages.md
- test/test_bibliography_block_pages/src/part3/section2/p3_s2_page.md
- test/test_bibliography_block_pages/src/references.md
- test/test_latex_rendering.jl
- test/test_parse_bibliography_block.jl
The `Pages` field now behaves exactly as `Pages` in `@contents` and `@index` blocks: all files are relative to the directory containing the current file.
Also, by popular demand, `@__FILE__` is supported to refer to the current file (even though `@contents` and `@index` does not support this feature.
Closes #22
> Fix behavior of `Pages` in `@bibliography` blocks

- test/test_latex_rendering.jl
Documenter changed how non-breaking spaces are written to LaTeX, see https://github.com/JuliaDocs/Documenter.jl/pull/2300
This checks the version of Documenter in the tests, so it works both with old and new versions of Documenter.
> Adapt tests to Documenter 1.1.2

- test/test_formatting.jl
- test/test_formatting/corporateauthor.bib
> Add test for "corporate authors"

- docs/src/syntax.md
- src/DocumenterCitations.jl
The release of `BibInternal v0.3.5` solved issue https://github.com/Humans-of-Julia/BibInternal.jl/issues/22 related to preprints. Our monkey-patch of `BibInternal.make_bibtex_entry` to work around this is no longer necessary.
The release also solved issue https://github.com/Humans-of-Julia/BibInternal.jl/pull/21, so the description of the workaround in the documentation can be removed.
Note that `BibInternal` is only an implicit dependency (via `Bibliography.jl`). The lowest compat-bound for `Bibliography.jl`, that is, `v0.2.15`, is compatible with `BibInternal v0.3.5`. So that version should be installed automatically. Someone would have to go out of their way to pin an older version of `BibInternal` in their environment. Dealing with any resulting bugs in that case is on them.
> Remove workarounds for bugs fixed in BibInternal 0.3.5

- NEWS.md
- Project.toml
- docs/latex/.gitignore
- docs/latex/Makefile
- docs/latex/biblatex.tex
- docs/latex/numeric.tex
- docs/latex/refs.bib
- docs/src/refs.bib
- docs/src/syntax.md
- src/DocumenterCitations.jl
- src/formatting.jl
- src/labeled_styles_utils.jl
- src/styles/authoryear.jl
- test/Project.toml
- test/test_formatting.jl
- test/test_formatting/urldate.bib
> Add support for `Urldate` field

- .github/workflows/ci.yml
- NEWS.md
- Project.toml
This is a pretty big release, see [NEWS.md](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/release-1.3.0/NEWS.md). To anyone relying on the [Internals](https://juliadocs.org/DocumenterCitations.jl/stable/internals/) for a custom style, it would be considered breaking. Hopefully, this will be the last release with such a significant change to the internals. If nothing comes up in the next couple of months, I would consider declaring the *documented* internals "stable" (covered by SemVer) in the `1.4.0` release, to be a bit more reliable for people with custom styles.
> Release 1.3.0

- NEWS.md
- Project.toml
- src/expand_bibliography.jl
- test/test_bibliography_block_pages.jl
- test/test_bibliography_block_pages/src/part3/section2/invalidpages.md
The names in `Pages` in a `@bibliography` block can now again be relative to the `docs/src` directory, which was the `1.2.x` behavior. A warning will be emitted that these should be updated.
This PR also extends the "upgrade instructions" for the `1.3.0` release in [NEWS.md](https://github.com/JuliaDocs/DocumenterCitations.jl/blob/mg/59-pages-fallback/NEWS.md) (which should have been in the original release)
Closes #59
> Add a fallback for `Pages` to behave as in pre-1.3

- NEWS.md
- Project.toml
- docs/src/refs.bib
- src/formatting.jl
- src/tex_to_markdown.jl
- test/test_formatting.jl
- test/test_formatting/invalid_doi.bib
- test/test_tex_to_markdown.jl
Warn about markdown links and invalid DOIs in the `.bib` file, as discussed in https://github.com/JuliaDocs/DocumenterCitations.jl/issues/59#issuecomment-1789525803 and https://github.com/JuliaDocs/DocumenterCitations.jl/issues/60#issuecomment-1790537993
> Warn about invalid bibtex

- .github/workflows/PkgEval.yml
- README.md
"Nightly" is a pretty moving target, so it doesn't make sense to check `PkgEval` all the time. However, we do want to check before making a release (since JuliaHub displays a badge [based on the last release](https://discourse.julialang.org/t/how-does-the-pkgeval-badge-work-on-juliahub/105662)).
Thus, we add a workflow that runs on `release-*` branches. In addition, it also runs on a special `pkgeval` branch. So, to check the status of `PkgEval`, we can just push a branch of that name (without a PR).
Closes #50
> Add workflow to check `PkgEval`

- NEWS.md
- src/formatting.jl
- test/test_formatting.jl
- test/test_formatting/alternative_non_articles.bib
This restores the DocumenterCitation 1.2 behavior of always being able to link to a URL as well as a DOI (for entries that define all required fields for their respective type).
Closes #63
> Auto-link both URL and DOI

- src/formatting.jl
- src/labeled_styles_utils.jl
- src/styles/authoryear.jl
- test/test_formatting.jl
Resolves https://github.com/JuliaDocs/DocumenterCitations.jl/issues/73 in a straight-up fashion.
Alternatively, one could add some preference for this, or add a dispatch on `style::Val{:stylesymbol}` for this to make users able to adapt the bibliography printing themselves.
> Add option to not specialcase `@article` type in href positioning

- src/labeled_styles_utils.jl
My use case is to be able to pass the `et_al` argument to limit the number of names
> Pass extra keyword arguments to format_names

- src/styles/authoryear.jl
- test/test_formatting.jl
This looked like an oversight because the argument name is the same in both functions.
The current behavior is this:
```julia
import DocumenterCitations
test_path = joinpath(dirname(dirname(pathof(DocumenterCitations))), "test/test_formatting/preprints.bib")
bib = DocumenterCitations.CitationBibliography(test_path)
b = first(values(bib.entries))
DocumenterCitations.format_published_in(b) # shows doi
DocumenterCitations.format_published_in(b, article_link_doi_in_title = true) # does not show doi
DocumenterCitations.format_authoryear_bibliography_reference(:authoryear, b) # shows doi around journal
DocumenterCitations.format_authoryear_bibliography_reference(:authoryear, b, article_link_doi_in_title = true) # shows doi around journal AND title
```
Showing the doi twice around both journal …
> pass `article_link_doi_in_title` to `format_published_in` in `format_authoryear_bibliography_reference`

- NEWS.md
- src/expand_bibliography.jl
- test/test_bibliography_block_pages.jl
In v1.10, Documenter changed paths in error messages from being relative to `make.jl` to being relative to the CWD, via the internal `Documenter.locrepr` function. See https://github.com/JuliaDocs/Documenter.jl/pull/2659.
This PR consistenly uses `Documenter.locrepr` for file paths in error messages, ensuring that `DocumenterCitations` is consistent with `Documenter` both pre-1.10 and post-1.10. See https://github.com/JuliaDocs/Documenter.jl/pull/2667#issuecomment-2760402462.
As a side effect, the location of a `@bibliography` block containing errors is now shown including line numbers in more situations.
> Show error file paths consistently with Documenter
